### ISSUE TITLE
Support "remote"-entities

### ISSUE THREAD

**Issue by pri-me** [unfoldedcircle/integration-home-assistant#23]
The "Remotes" section in the web configurator currently supports only IR-remotes. 

This is a request for it to also support the HA "remote" enitity exposed by some integrations (e.g. `remote.philips_tv`).

Currently, it is necessary to create a script for each button in order to use the remote via HA. This is not only tedious to create but also problematic since an activity only allows 50 active entities and each press is an entity. 

With remote entity support, you would just add the remote entity and thus expose all commands to Remote Two like with IR remotes.

**Comment by DavidSpek** [comment]
This code comment seems somewhat related: https://github.com/unfoldedcircle/integration-home-assistant/blob/47903d484d09ee0f9534caaf553dfd625d06b2b7/src/client/service/media_player.rs#L87C44-L87C44

**Comment by mvdwetering** [comment]
This would be cool, but not sure how UC would get to know about the supported commands for that specific Remote entity. Unfortunately  HA has no mechanism to indicate which commands are supported.

There was an architectural discussion about something like this, but that seems to have died out https://github.com/home-assistant/architecture/discussions/875

**Comment by albaintor** [comment]
> This would be cool, but not sure how UC would get to know about the supported commands for that specific Remote entity. Unfortunately HA has no mechanism to indicate which commands are supported.
> 
> There was an architectural discussion about something like this, but that seems to have died out [home-assistant/architecture#875](https://github.com/home-assistant/architecture/discussions/875)
> 
> Edit: that being said, just having a textbox or something where we could just copy-paste the supported commands from the Home Assistant documentation would be a great help.

Hi, sure but one could be the same behaviour as the "send command" function where you type the corresponding command in plain text.
Actually this is a big limitation because the media player component has limited functions (play/pause, next/previous) and not the additional commands (such as arrow keys/OK commands).
Thank you

**Comment by zehnm** [comment]
To integrate HA remote-entites requires support in the integration API, core services and web-configurator. They don't fully match the current internal IR remote-entity and will require additional logic in the core services. If they currently slip through as available entities, then this is a bug and not a feature :-)
Only the [documented entities in the Core-Api](https://github.com/unfoldedcircle/core-api/tree/main/doc/entities) are supported.

Supporting more HA entities, including remotes, is planned though.

**Comment by antifuchs** [comment]
I've worked around this limitation in a slightly annoying way, which nevertheless seems to work a bit better than the built-in appletv remote for e.g. play/pause buttons on the remote UI (e.g. https://github.com/unfoldedcircle/feature-and-bug-tracker/issues/315). Here's what I did:

1. Make one button helper entity per button on the appletv remote. Name them `Home Theater Remote -  <command>` This is annoying to do, but you only have do it once. I don't think there's a way to export the yaml for the buttons I created, otherwise I'd paste it here to ease your suffering.
2. Make an automation that hooks the appletv remote entity up to each of those buttons:
  ```yaml
id: '1708186917053'
alias: Translate AppleTV buttons to remote events
description: ''
trigger:
  - platform: state
    entity_id:
      - input_button.home_theater_cursor_up
      - input_button.home_theater_cursor_down
      - input_button.home_theater_cursor_left
      - input_button.home_theater_cursor_right
      - input_button.home_theater_ok
      - input_button.home_theater_remote_menu
      - input_button.home_theater_remote_turn_off
      - input_button.home_theater_remote_turn_on
      - input_button.home_theater_remote_play_pause
      - input_button.home_theater_remote_home
      - input_button.home_theater_remote_volume_down
      - input_button.home_theater_remote_volume_up
      - input_button.home_theater_remote_channel_down
      - input_button.home_theater_remote_channel_up
      - input_button.home_theater_remote_next
      - input_button.home_theater_remote_previous
condition: []
action:
  - service: logbook.log
    metadata: {}
    data:
      name: hi
      message: |-
        {{ trigger.from_state.attributes.friendly_name|regex_replace(
          find='Home Theater Remote - ', 
          replace='') }}
    alias: Log command we're sending
  - service: remote.send_command
    metadata: {}
    data:
      command:
        - |-
          {{ trigger.from_state.attributes.friendly_name|regex_replace(
              find='Home Theater Remote - ', 
              replace='') 
          }}
    target:
      entity_id: remote.home_theater
mode: single
  ```
3. Reload the home-assistant integration on the remote & import all the "Home Theater Remote - " buttons
4. Then, you can add those to your appletv activity & use the buttons on operations that should always work (e.g. play/pause, the menu & select button, skip forward/back)

I think until we have reliable reconnection working in the appletv remote integration, this works a lot better: You still wait for the remote to wake up, but it can send the command to hass on the first try & that reliably pauses media!
